### PR TITLE
Initial dependency was added. Also create gitignore to exclude vendors folder

### PR DESCRIPTION
**Pull request by vbyndych**
- Now dependency is obvious from the code and everybody can install project as simple as _composer install_

If you have any ideas or remarks please let me know.

### CODE REVIEW

**Review by 4ernovm — CHANGES_REQUESTED** [review]
Committing composer.lock file in a project that is meant to be a part of other project is not a good idea. I believe you can find many posts, articles and discussions on that topic. And since this project originally created as a Laravel package composer.lock should be removed.

**Comment by vbyndych** [comment]
Could you provide any examples, because first link in a google is http://stackoverflow.com/a/18903646

**Comment by 4ernovm** [comment]
I have no reasons not to trust to the author of Composer. But the fact that you CAN do something doesn't always means you SHOULD. 

Original Composer docs says following
"This can help your team to always test against the same dependency versions."
(https://getcomposer.org/doc/02-libraries.md#lock-file)

But really, how many libraries have you seen that are using explicit dependencies? It's always about some range of versions. So I think it's even better to be able to test it against different versions of dependencies. This will give you a chance to get some dependency-related error earlier than someone who will use your lib. Cuz, as Seldaek stated in the link you've provided, composer.lock in a lib will be ignored eventually. Which means different dependencies versions. Which gives a room for errors. If you have such an important dependency that change of it's version will crash your lib - put it in composer.json. No? ;)

P.S. "in general I guess it's good to gitignore it" 
https://github.com/composer/composer/issues/2461#issuecomment-29282932

**Comment by vbyndych** [comment]
@4ernovm Thank you for detailed explanation. I've updated my PR

**Pull request merged**
